name: pypi

on:
  push:
    tags:
      - v*

jobs:
  test:
    strategy:
      matrix:
        python:
          - version: "3.8"
            toxenv: "py38"
          - version: "3.9"
            toxenv: "py39"
          - version: "3.10"
            toxenv: "py310"
          - version: "3.11"
            toxenv: "py311"
          - version: "3.12"
            toxenv: "py312"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
      - run: python -m pip install --upgrade setuptools pip 'tox<4' virtualenv
      - run: tox -e ${{ matrix.python.toxenv }}
  pypi:
    needs: test
    runs-on: ubuntu-latest
	environment:
      name: pypi
      url: https://pypi.org/p/testify
    permissions:
      id-token: write
    steps:
      - uses: pypa/gh-action-pypi-publish@v1.8.10
